### ISSUE TITLE
Can I generate some moire pattern and put it to some picture to imitate true moire pattern?

### ISSUE THREAD

**Issue by daeing** [TAdeJong/moire-lattice-generator#4]
Can I generate some moire pattern and put it to some picture to imitate true moire pattern?

**Comment by daeing** [comment]
Thanks for your reply. I'm so sorry, I didn't make my question clear. But your answer solve my another confused question, many thanks.
I was wondering if I can use this way to generate a lattice, and then add lattice to another scene image(or some another combine way), then the added image is same like the scene image with true moire pattern (scene image show on screen and then taken by camera).

**Comment by daeing** [comment]
> Yes, this should be possible, by first using matplotlib's `plt.imshow()` for your original image, and then add the generated moiré image, either with a global value for the transparency `alpha=`, or by using the transparency tricks described in the docs: https://moire-lattice-generator.readthedocs.io/en/latest/source/Transparency.html

Many thanks, I'll have try!

**Comment by TAdeJong** [comment]
I'll close this as your questions seem answered, but feel free to reopen or reach out if you run into other issues.
